db.url=jdbc:mysql://192.168.216.128:3306/movie_ticket_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
db.user=root
db.password=12345
